import sys, os
root = r"C:\Users\Jeff\Documents\Projects\Stardee Valoo\TheLongestYear"
gen = open(sys.argv[1], encoding='utf-8').read()

head = '''using System;
using System.Collections.Generic;

namespace TheLongestYear.Core;

/// <summary>Weekly yield bases for every domain besides fish and forage, for <see cref="AskBands"/>.
/// Jeff's rulings, 2026-09-04. The Crops, MonsterDrops and Minerals tables are GENERATED by
/// tools/fish-sim/gen_tables.py from the game's Data/Crops, Data/Monsters and Data/Objects dumps;
/// regenerate them there, never edit a number by hand. CrabPot and Stations are hand tables
/// worked from CrabPot.DayUpdate and Data/CraftingRecipes with the reasoning on every row.</summary>
public static class QuantityBasisTables
{
    /// <summary>Crab pot catch per week at 10 pots in the right zone, Jeff 2026-09-04 ("10 per
    /// season"). CrabPot.DayUpdate: 20% junk first, then the trap rows of Data/Fish in file order,
    /// each rolling its own chance, first pass wins. Per pot-day: Lobster .04, Crab .076, Oyster
    /// .103, Clam .087, Shrimp .099, Cockle .119, Mussel .097; Snail .20, Crayfish .21, Periwinkle
    /// .215. Times 70 pot-days. Shellfish that are also beach forage ADD this to their measured
    /// forage mean (QuantityAskPass).</summary>
    public static readonly IReadOnlyDictionary<string, double> CrabPot = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)715"] = 2.8,    // Lobster
        ["(O)717"] = 5.3,    // Crab
        ["(O)723"] = 7.2,    // Oyster
        ["(O)372"] = 6.1,    // Clam
        ["(O)720"] = 6.9,    // Shrimp
        ["(O)718"] = 8.3,    // Cockle
        ["(O)719"] = 6.8,    // Mussel
        ["(O)721"] = 14.0,   // Snail
        ["(O)716"] = 14.7,   // Crayfish
        ["(O)722"] = 15.0,   // Periwinkle
    };

    /// <summary>Station and animal output per week, Jeff 2026-09-04: counts follow what each
    /// station costs and when it unlocks (Data/CraftingRecipes), and animal products are meant to
    /// be a stretch: a Big Coop or Big Barn of eight. Furnace output is ore-limited, not
    /// furnace-limited. Books and artifacts stay single asks and have no row.</summary>
    public static readonly IReadOnlyDictionary<string, double> Stations = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        // Furnace (Mining 2, 20 copper ore + 25 stone): ore and coal are the limit, not furnaces.
        // From the mine-day model (Mines table): about 400 ore and 86 coal a week in the band, so
        // 80 bars; gold floors are slower and meaner, Skull Cavern ore is a judgement 70 a week.
        ["(O)334"] = 80,   // Copper Bar
        ["(O)335"] = 80,   // Iron Bar
        ["(O)336"] = 60,   // Gold Bar
        ["(O)337"] = 14,   // Iridium Bar
        ["(O)338"] = 40,   // Refined Quartz (Quartz basis 80, one each)
        // Tapper (Foraging 4, 40 wood + 2 copper bars): 10 tappers.
        ["(O)724"] = 8,    // Maple Syrup, 9 days
        ["(O)725"] = 10,   // Oak Resin, 7 days
        ["(O)726"] = 14,   // Pine Tar, 5 days
        ["(O)92"] = 99,    // Sap, any tree
        // Animals: Big Coop / Big Barn of eight (Jeff: the smaller counts were "well too easy").
        ["(O)176"] = 28,   // Egg (white), 8 chickens a day split across colours
        ["(O)180"] = 28,   // Egg (brown)
        ["(O)174"] = 28,   // Large Egg (white), at friendship
        ["(O)182"] = 28,   // Large Egg (brown)
        ["(O)442"] = 28,   // Duck Egg, every other day
        ["(O)444"] = 7,    // Duck Feather
        ["(O)446"] = 2,    // Rabbit's Foot, rare
        ["(O)440"] = 18,   // Wool, 8 sheep every 3 days
        ["(O)184"] = 56,   // Milk, 8 cows a day
        ["(O)186"] = 28,   // Large Milk
        ["(O)436"] = 28,   // Goat Milk, every other day
        ["(O)438"] = 14,   // L. Goat Milk
        ["(O)430"] = 50,   // Truffle, 8 pigs, not in Winter
        // Mayonnaise Machine (Farming 2): egg-limited.
        ["(O)306"] = 56,   // Mayonnaise
        ["(O)307"] = 28,   // Duck Mayonnaise
        // Cheese Press (Farming 6): milk-limited.
        ["(O)424"] = 56,   // Cheese
        ["(O)426"] = 28,   // Goat Cheese
        // Loom (Farming 7): wool-limited.
        ["(O)428"] = 18,   // Cloth
        // Bee House (Farming 3, iron bar + maple syrup): 10 houses, 4 days.
        ["(O)340"] = 17,   // Honey
        // Preserves Jar (Farming 4): 10 jars, 3 days, crop input is a full stack.
        ["(O)344"] = 23,   // Jelly
        ["(O)342"] = 23,   // Pickles
        // Keg (Farming 8, copper + iron + oak resin): 5 kegs.
        ["(O)348"] = 5,    // Wine, 7 days
        ["(O)350"] = 9,    // Juice, 4 days
        ["(O)346"] = 20,   // Beer, 1.75 days
        ["(O)303"] = 15,   // Pale Ale, 2.25 days
        ["(O)459"] = 17,   // Mead, honey-limited
        ["(O)395"] = 20,   // Coffee, 5 beans each
        ["(O)614"] = 20,   // Green Tea, 10 tea bushes
        // Oil Maker (Farming 8, gold bar): truffle-limited.
        ["(O)432"] = 5,    // Truffle Oil
        // Dehydrator / Fish Smoker (bought, cheap): 5 machines, one a day each.
        ["(O)DriedFruit"] = 35,
        ["(O)DriedMushrooms"] = 35,
        ["(O)Raisins"] = 35,
        ["(O)SmokedFish"] = 35,
        // Roe: Fish Pond, one pond of a common fish.
        ["(O)812"] = 10,   // Roe
        ["(O)447"] = 10,   // Aged Roe
        ["(O)445"] = 5,    // Caviar
    };

'''
tail = '''
}
'''
open(os.path.join(root, 'src/TheLongestYear.Core/QuantityBasisTables.cs'), 'w', encoding='utf-8').write(head + gen + tail)

p = os.path.join(root, 'src/TheLongestYear.Core/QuantityAskPass.cs'); s = open(p, encoding='utf-8').read()
old = '''    public static bool Covers(string? itemId)
        => FishAskBasis.Covers(itemId) || ForageAskBasis.Covers(itemId);

    private static double? BasisByDeadline(string itemId, Season? deadline)
        => FishAskBasis.BasisByDeadline(itemId, deadline) ?? ForageAskBasis.BasisByDeadline(itemId, deadline);
}'''
new = '''    public static bool Covers(string? itemId)
    {
        if (itemId == null) return false;
        string id = BundleParsing.NormalizeItemId(itemId);
        return FishAskBasis.Covers(id) || ForageAskBasis.Covers(id)
               || QuantityBasisTables.CrabPot.ContainsKey(id) || QuantityBasisTables.Crops.ContainsKey(id)
               || QuantityBasisTables.MonsterDrops.ContainsKey(id) || QuantityBasisTables.Stations.ContainsKey(id)
               || QuantityBasisTables.Minerals.ContainsKey(id);
    }

    /// <summary>Fish first (it knows seasons), then forage plus crab pot (a shellfish is gathered
    /// AND trapped, so the two add), then the flat weekly tables.</summary>
    private static double? BasisByDeadline(string itemId, Season? deadline)
    {
        string id = BundleParsing.NormalizeItemId(itemId);
        double? fish = FishAskBasis.BasisByDeadline(id, deadline);
        if (fish != null) return fish;
        double? forage = ForageAskBasis.BasisByDeadline(id, deadline);
        double? pot = QuantityBasisTables.CrabPot.TryGetValue(id, out double p) ? p : null;
        if (forage != null || pot != null) return (forage ?? 0) + (pot ?? 0);
        foreach (IReadOnlyDictionary<string, double> table in new[] { QuantityBasisTables.Crops, QuantityBasisTables.MonsterDrops, QuantityBasisTables.Stations, QuantityBasisTables.Minerals })
            if (table.TryGetValue(id, out double basis)) return basis;
        return null;
    }
}'''
assert old in s; s = s.replace(old, new, 1)
s = s.replace('''/// <summary>Gives every fish and forage slot on a finished bundle its banded ask
/// (<see cref="FishAskBasis"/> or <see cref="ForageAskBasis"/> x <see cref="AskBands"/>)''', '''/// <summary>Gives every slot with a known weekly yield on a finished bundle its banded ask
/// (<see cref="FishAskBasis"/>, <see cref="ForageAskBasis"/> or <see cref="QuantityBasisTables"/>
/// x <see cref="AskBands"/>)''')
open(p, 'w', encoding='utf-8').write(s)

p = os.path.join(root, 'src/TheLongestYear.Core/BundleSlotFiller.cs'); s = open(p, encoding='utf-8').read()
a = s.index('            case PoolDomain.QualityCrops:\n                return tuning.QualityCropStack;')
b = s.index('            default:\n                return 1;')
s = s[:a] + '''            // Every domain rolls one here. Fish, forage, crops (Quality Crops included), monster
            // drops, crab pot, station and mineral asks take basis x band later in
            // QuantityAskPass, on the finished board (2026-09-04); the old price-banded monster
            // roll and the fixed x5 gold crop went with it. The tuning fields stay for config
            // compatibility.
''' + s[b:]
open(p, 'w', encoding='utf-8').write(s)

p = os.path.join(root, 'src/TheLongestYear.Core/StackScaling.cs'); s = open(p, encoding='utf-8').read()
s = s.replace('''            // A banded fish or forage slot already carries its step's ask (QuantityAskPass);
            // scaling it again would apply the same dial twice.''', '''            // A banded slot (fish, forage, crop, monster drop, crab pot, station, mineral) already
            // carries its step's ask (QuantityAskPass); scaling it again would apply the dial twice.''')
open(p, 'w', encoding='utf-8').write(s)
print('ok')
