using System;
using System.Collections.Generic;

namespace TheLongestYear.Core;

/// <summary>Weekly yield bases for every domain besides fish and forage, for <see cref="AskBands"/>.
/// Jeff's rulings, 2026-09-04. The Crops, MonsterDrops and Minerals tables are GENERATED by
/// tools/fish-sim/gen_tables.py from the game's Data/Crops, Data/Monsters and Data/Objects dumps;
/// regenerate them there, never edit a number by hand. CrabPot and Stations are hand tables
/// worked from CrabPot.DayUpdate and Data/CraftingRecipes with the reasoning on every row.</summary>
public static class QuantityBasisTables
{
    /// <summary>Crab pot catch per week at 10 pots in the right zone, Jeff 2026-09-04 ("10 per
    /// season"). CrabPot.DayUpdate: 20% junk first, then the trap rows of Data/Fish in file order,
    /// each rolling its own chance, first pass wins. Per pot-day: Lobster .04, Crab .076, Oyster
    /// .103, Clam .087, Shrimp .099, Cockle .119, Mussel .097; Snail .20, Crayfish .21, Periwinkle
    /// .215. Times 70 pot-days. Shellfish that are also beach forage ADD this to their measured
    /// forage mean (QuantityAskPass).</summary>
    public static readonly IReadOnlyDictionary<string, double> CrabPot = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)715"] = 2.8,    // Lobster
        ["(O)717"] = 5.3,    // Crab
        ["(O)723"] = 7.2,    // Oyster
        ["(O)372"] = 6.1,    // Clam
        ["(O)720"] = 6.9,    // Shrimp
        ["(O)718"] = 8.3,    // Cockle
        ["(O)719"] = 6.8,    // Mussel
        ["(O)721"] = 14.0,   // Snail
        ["(O)716"] = 14.7,   // Crayfish
        ["(O)722"] = 15.0,   // Periwinkle
    };

    /// <summary>Station and animal output per week, Jeff 2026-09-04: counts follow what each
    /// station costs and when it unlocks (Data/CraftingRecipes), and animal products are meant to
    /// be a stretch: a Big Coop or Big Barn of eight. Furnace output is ore-limited, not
    /// furnace-limited. Books and artifacts stay single asks and have no row.</summary>
    public static readonly IReadOnlyDictionary<string, double> Stations = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        // Furnace (Mining 2, 20 copper ore + 25 stone): ore and coal are the limit, not furnaces.
        // From the mine-day model (Mines table): about 400 ore and 86 coal a week in the band, so
        // 80 bars; gold floors are slower and meaner, Skull Cavern ore is a judgement 70 a week.
        ["(O)334"] = 80,   // Copper Bar
        ["(O)335"] = 80,   // Iron Bar
        ["(O)336"] = 60,   // Gold Bar
        ["(O)337"] = 14,   // Iridium Bar
        ["(O)338"] = 40,   // Refined Quartz (Quartz basis 80, one each)
        // Tapper (Foraging 4, 40 wood + 2 copper bars): 10 tappers.
        ["(O)724"] = 8,    // Maple Syrup, 9 days
        ["(O)725"] = 10,   // Oak Resin, 7 days
        ["(O)726"] = 14,   // Pine Tar, 5 days
        ["(O)92"] = 99,    // Sap, any tree
        // Animals: Big Coop / Big Barn of eight (Jeff: the smaller counts were "well too easy").
        ["(O)176"] = 28,   // Egg (white), 8 chickens a day split across colours
        ["(O)180"] = 28,   // Egg (brown)
        ["(O)174"] = 14,   // Large Egg (white): the same hens lay either size, so half (Codex review)
        ["(O)182"] = 14,   // Large Egg (brown)
        ["(O)442"] = 28,   // Duck Egg, every other day
        ["(O)444"] = 7,    // Duck Feather
        ["(O)446"] = 2,    // Rabbit's Foot, rare
        ["(O)440"] = 18,   // Wool, 8 sheep every 3 days
        ["(O)184"] = 56,   // Milk, 8 cows a day
        ["(O)186"] = 14,   // Large Milk: the same cows, half
        ["(O)436"] = 28,   // Goat Milk, every other day
        ["(O)438"] = 7,    // L. Goat Milk: the same goats, half
        ["(O)430"] = 50,   // Truffle, 8 pigs, not in Winter
        // Mayonnaise Machine (Farming 2): egg-limited.
        ["(O)306"] = 56,   // Mayonnaise
        ["(O)307"] = 28,   // Duck Mayonnaise
        // Cheese Press (Farming 6): milk-limited.
        ["(O)424"] = 56,   // Cheese
        ["(O)426"] = 28,   // Goat Cheese
        // Loom (Farming 7): wool-limited.
        ["(O)428"] = 18,   // Cloth
        // Bee House (Farming 3, iron bar + maple syrup): 10 houses, 4 days.
        ["(O)340"] = 17,   // Honey
        // Preserves Jar (Farming 4): 10 jars, 3 days, crop input is a full stack.
        ["(O)344"] = 23,   // Jelly
        ["(O)342"] = 23,   // Pickles
        // Keg (Farming 8, copper + iron + oak resin): 5 kegs.
        ["(O)348"] = 5,    // Wine, 7 days
        ["(O)350"] = 9,    // Juice, 4 days
        ["(O)346"] = 20,   // Beer, 1.75 days
        ["(O)303"] = 15,   // Pale Ale, 2.25 days
        ["(O)459"] = 17,   // Mead, honey-limited
        ["(O)395"] = 20,   // Coffee, 5 beans each
        ["(O)614"] = 20,   // Green Tea, 10 tea bushes
        // Oil Maker (Farming 8, gold bar): truffle-limited.
        ["(O)432"] = 5,    // Truffle Oil
        // Dehydrator / Fish Smoker (bought, cheap): 5 machines, one a day each, so 35 RUNS a week.
        //
        // A run is not a unit, though, and for the Dehydrator that is the whole difference: it
        // eats FIVE fruit or mushrooms per dried good (Data/Machines), so 35 of them would need
        // 175 inputs in a week. Nothing forages or grows at that rate, so the inputs are the real
        // ceiling, not the machines. A good week of mushrooms is the cave emptied daily plus what
        // the woods give, on the order of 35, which is 7 dried (Jeff, 2026-09-21, after a board
        // asked for 13 Dried Mushrooms, i.e. 65 mushrooms).
        //
        // The Fish Smoker is one fish in, one out, so 35 runs really is 35 units and its row is
        // unchanged. A flavored slot never reads these numbers at all: it sizes the ask from the
        // fruit or fish it names (FlavoredSlotRules.BasisFor). These are the "any" slots' rows.
        ["(O)DriedFruit"] = 7,
        ["(O)DriedMushrooms"] = 7,
        ["(O)Raisins"] = 7,
        ["(O)SmokedFish"] = 35,
        // Roe: Fish Pond, one pond of a common fish.
        ["(O)812"] = 10,   // Roe
        ["(O)447"] = 10,   // Aged Roe
        ["(O)445"] = 5,    // Caviar
    };

    /// <summary>Raw resources a week of chopping, tilling and stump-clearing yields, so Extreme does
    /// not sit Fiber x2 and Clay x2 next to Stone x79 (Codex review, 2026-09-04). Stone is in Mines.</summary>
    public static readonly IReadOnlyDictionary<string, double> Resources = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)388"] = 99,   // Wood
        ["(O)771"] = 99,   // Fiber, weeds and Fiber Seeds
        ["(O)709"] = 40,   // Hardwood, Secret Woods stumps and the farm's large stumps
        ["(O)330"] = 20,   // Clay, tilling and Duggies
    };

    /// <summary>What a week in the mines yields, from one modelled "mine day": 10 floors cleared,
    /// 300 clear tiles a floor, a stone on 20% of them (populateLevel: 10 to 30%), Mining 5, luck 0.
    /// Chances read off the decompile (tools/fish-sim/mineday.py has the arithmetic): ore nodes on
    /// 2.9% of stones dropping 1 to 3 (createLitterObject, breakStone); a 5% x 0.8 ore roll on plain
    /// stones by floor band (checkStoneForItems, getOreIdForLevel); coal on 8% of the 668/670 stones
    /// and a quarter of the ore roll; an area geode on 2.2% of stones and an Omni Geode on 0.5%; floor
    /// items on 0.25% of clear tiles, three quarters Quartz and the rest the area's crystal
    /// (getRandomItemForThisLevel); gem nodes on 0.15% + level/24000 of tiles, one of six gems by
    /// band; a Diamond node on 0.025% + level/120000 of stones past floor 50. Quartz adds the Stone
    /// Golem drop from the same floors. Jeff 2026-09-04: "quartz is much more common".
    ///
    /// MEASURED 2026-09-16 (tly_minesweep, floors 1 to 160, seven day counters, every stone broken,
    /// every geode cracked, bare farmer; docs/superpowers/notes/minesweep-2026-09-16.md): the stone
    /// count, the ore, the geodes and the crystals came out where the model put them, and four rows
    /// did not. Jeff applied the measured numbers the same day; those rows say so.</summary>
    public static readonly IReadOnlyDictionary<string, double> Mines = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)378"] = 99,   // Copper Ore, 435 a week on floors 1-39
        ["(O)380"] = 99,   // Iron Ore, 398 on 40-79
        ["(O)384"] = 99,   // Gold Ore, 398 on 80-119
        ["(O)386"] = 70,   // Iridium Ore, Skull Cavern, judgement 10 a day (Iridium Bat gives more)
        ["(O)382"] = 99,   // Coal: MEASURED 312 to 335 a week in every band (coal nodes plus the plain-stone roll); the model's 86 was 3.5x low
        ["(O)390"] = 99,   // Stone
        ["(O)535"] = 92,   // Geode, floors 1-39
        ["(O)536"] = 92,   // Frozen Geode, 40-79
        ["(O)537"] = 92,   // Magma Geode, 80-119
        ["(O)749"] = 21,   // Omni Geode
        ["(O)80"] = 35,    // Quartz: MEASURED 27 to 34 a week (floor items, Stone Golems, geodes); the model's 80 was 2.5x high
        ["(O)86"] = 18,    // Earth Crystal: 13 floor items + 5 from Geodes
        ["(O)84"] = 27,    // Frozen Tear: MEASURED 27 a week on floors 41 to 80 once geodes are cracked
        ["(O)82"] = 18,    // Fire Quartz
        // Gems: MEASURED 4 to 9 a week in the gem's best band, geodes cracked. The model's gem-node
        // rate (0.15% of tiles + level/24000) was 2 to 3x what the generator places; a geode is
        // mostly ore, stone, clay and the area crystal, so cracking barely moves these.
        ["(O)66"] = 9,     // Amethyst, gem nodes plus Green Slimes (measured 9)
        ["(O)68"] = 7,     // Topaz (measured 7)
        ["(O)62"] = 7,     // Aquamarine (measured 6)
        ["(O)70"] = 7,     // Jade (measured 7)
        ["(O)60"] = 7,     // Emerald (measured 8)
        ["(O)64"] = 7,     // Ruby (measured 6)
        ["(O)72"] = 3,     // Diamond
    };

    /// <summary>Crops, Jeff 2026-09-04: 100 tiles and no cost cap (seed makers, the stash and JP upgrades are
    /// what multi-loop play is for), so only seed availability limits a crop. A shop seed is a full stack.</summary>
    public static readonly IReadOnlyDictionary<string, double> Crops = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)24"] = 99,   // Parsnip: shop seed
        ["(O)188"] = 99,   // Green Bean: shop seed
        ["(O)190"] = 99,   // Cauliflower: shop seed
        ["(O)192"] = 99,   // Potato: shop seed
        ["(O)248"] = 99,   // Garlic: shop seed
        ["(O)271"] = 99,   // Unmilled Rice: shop seed
        ["(O)250"] = 99,   // Kale: shop seed
        ["(O)252"] = 99,   // Rhubarb: shop seed
        ["(O)400"] = 99,   // Strawberry: shop seed
        ["(O)254"] = 99,   // Melon: shop seed
        ["(O)256"] = 99,   // Tomato: shop seed
        ["(O)258"] = 99,   // Blueberry: shop seed
        ["(O)260"] = 99,   // Hot Pepper: shop seed
        ["(O)262"] = 99,   // Wheat: shop seed
        ["(O)264"] = 99,   // Radish: shop seed
        ["(O)266"] = 99,   // Red Cabbage: shop seed
        ["(O)268"] = 99,   // Starfruit: shop seed
        ["(O)433"] = 20,   // Coffee Bean: the only in-loop seed is a 1% Dust Sprite drop, so supply-limited despite regrowing 4 every 2 days (a Summer board asked 38 on Normal)
        ["(O)90"] = 99,   // Cactus Fruit: shop seed
        ["(O)270"] = 99,   // Corn: shop seed
        ["(O)304"] = 99,   // Hops: shop seed
        ["(O)398"] = 99,   // Grape: shop seed
        ["(O)300"] = 99,   // Amaranth: shop seed
        ["(O)272"] = 99,   // Eggplant: shop seed
        ["(O)274"] = 99,   // Artichoke: shop seed
        ["(O)276"] = 99,   // Pumpkin: shop seed
        ["(O)278"] = 99,   // Bok Choy: shop seed
        ["(O)280"] = 99,   // Yam: shop seed
        ["(O)282"] = 99,   // Cranberries: shop seed
        ["(O)284"] = 99,   // Beet: shop seed
        ["(O)454"] = 5,   // Ancient Fruit: seed is a rare artifact, 28 days then weekly; about five a year from one plant
        ["(O)591"] = 99,   // Tulip: shop seed
        ["(O)597"] = 99,   // Blue Jazz: shop seed
        ["(O)376"] = 99,   // Poppy: shop seed
        ["(O)593"] = 99,   // Summer Spangle: shop seed
        ["(O)421"] = 99,   // Sunflower: shop seed
        ["(O)595"] = 99,   // Fairy Rose: shop seed
        ["(O)417"] = 16,   // Sweet Gem Berry: Rare Seed is cart-only, Spring and Summer, one per visit, 2 a week with an upgraded cart
        ["(O)Carrot"] = 30,   // Carrot: Raccoon / tilling seeds, not buyable
        ["(O)SummerSquash"] = 30,   // Summer Squash: Raccoon / tilling seeds
        ["(O)Broccoli"] = 30,   // Broccoli: Raccoon / tilling seeds
        ["(O)Powdermelon"] = 30,   // Powdermelon: Raccoon / tilling seeds
    };

    /// <summary>Monster drops, Jeff 2026-09-04: 60 kills a day for 7 days of the best monster a loop can reach
    /// (mines and Skull Cavern; volcano, island and the Qi dangerous-mines roster excluded), every drop in
    /// Data/Monsters, chances summed per item. Capped at a stack.</summary>
    public static readonly IReadOnlyDictionary<string, double> MonsterDrops = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)66"] = 6.3,   // Amethyst: Green Slime, 6.3 expected
        ["(O)114"] = 2.1,   // Ancient Seed: Grub, 2.1 expected
        ["(O)767"] = 99.0,   // Bat Wing: Lava Bat, 672.0 expected
        ["(O)787"] = 7.0,   // Battery Pack: Iridium Bat, 7.0 expected
        ["(O)287"] = 99.0,   // Bomb: Lava Crab, 168.0 expected
        ["(O)881"] = 99.0,   // Bone Fragment: Skeleton, 462.0 expected
        ["(O)293"] = 12.6,   // Brick Floor: Shadow Guy, 12.6 expected
        ["(O)684"] = 99.0,   // Bug Meat: Fly, 378.0 expected
        ["(O)286"] = 99.0,   // Cherry Bomb: Rock Crab, 168.0 expected
        ["(O)105"] = 8.4,   // Chewing Stick: Duggy, 8.4 expected
        ["(O)428"] = 35.0,   // Cloth: Mummy, 35.0 expected
        ["(O)382"] = 99.0,   // Coal: Dust Spirit, 210.0 expected
        ["(O)433"] = 4.2,   // Coffee Bean: Dust Spirit, 4.2 expected
        ["(O)334"] = 16.8,   // Copper Bar: Shadow Guy, 16.8 expected
        ["(O)378"] = 84.0,   // Copper Ore: Metal Head, 84.0 expected
        ["(O)717"] = 99.0,   // Crab: Lava Crab, 105.0 expected
        ["(O)732"] = 70.0,   // Crab Cakes: Iridium Crab, 70.0 expected
        ["(O)414"] = 8.4,   // Crystal Fruit: Dust Spirit, 8.4 expected
        ["(O)72"] = 4.2,   // Diamond: Sludge, 4.2 expected
        ["(O)96"] = 2.1,   // Dwarf Scroll I: Green Slime, 2.1 expected
        ["(O)97"] = 2.1,   // Dwarf Scroll II: Dust Spirit, 2.1 expected
        ["(O)98"] = 6.3,   // Dwarf Scroll III: Frost Jelly, 6.3 expected
        ["(O)86"] = 42.0,   // Earth Crystal: Duggy, 42.0 expected
        ["(O)349"] = 7.0,   // Energy Tonic: Iridium Bat, 7.0 expected
        ["(O)84"] = 8.4,   // Frozen Tear: Dust Spirit, 8.4 expected
        ["(O)535"] = 99.0,   // Geode: Duggy, 105.0 expected
        ["(O)156"] = 33.6,   // Ghostfish: Ghost, 33.6 expected
        ["(O)336"] = 21.0,   // Gold Bar: Squid Kid, 21.0 expected
        ["(O)153"] = 42.0,   // Green Algae: Green Slime, 42.0 expected
        ["(O)386"] = 99.0,   // Iridium Ore: Iridium Bat, 245.0 expected
        ["(O)335"] = 8.4,   // Iron Bar: Shadow Guy, 8.4 expected
        ["(O)380"] = 84.0,   // Iron Ore: Metal Head, 84.0 expected
        ["(O)70"] = 8.4,   // Jade: Frost Jelly, 8.4 expected
        ["(O)773"] = 7.0,   // Life Elixir: Iridium Bat, 7.0 expected
        ["(O)288"] = 21.0,   // Mega Bomb: Squid Kid, 21.0 expected
        ["(O)243"] = 5.6,   // Miner's Treat: Mummy, 5.6 expected
        ["(O)749"] = 99.0,   // Omni Geode: Carbon Ghost, 138.6 expected
        ["(O)579"] = 2.1,   // Prehistoric Scapula: Skeleton, 2.1 expected
        ["(O)80"] = 42.0,   // Quartz: Stone Golem, 42.0 expected
        ["(O)338"] = 33.6,   // Refined Quartz: Ghost, 33.6 expected
        ["(O)273"] = 42.0,   // Rice Shoot: Grub, 42.0 expected
        ["(O)92"] = 99.0,   // Sap: Frost Jelly, 210.0 expected
        ["(O)766"] = 99.0,   // Slime: Big Slime, 961.8 expected
        ["(O)768"] = 99.0,   // Solar Essence: Ghost, 441.0 expected
        ["(O)226"] = 8.4,   // Spicy Eel: Serpent, 8.4 expected
        ["(O)814"] = 84.0,   // Squid Ink: Squid Kid, 84.0 expected
        ["(O)390"] = 99.0,   // Stone: Stone Golem, 378.0 expected
        ["(O)329"] = 8.4,   // Stone Floor: Shadow Guy, 8.4 expected
        ["(O)203"] = 16.8,   // Strange Bun: Shadow Guy, 16.8 expected
        ["(O)769"] = 99.0,   // Void Essence: Shadow Shaman, 399.0 expected
        ["(O)157"] = 42.0,   // White Algae: Sludge, 42.0 expected
        ["(O)412"] = 33.6,   // Winter Root: Frost Jelly, 33.6 expected
        ["(O)280"] = 12.6,   // Yam: Duggy, 12.6 expected
    };

    /// <summary>MEASURED caps over <see cref="MonsterDrops"/> (Jeff, 2026-09-16). The generated table
    /// assumes 420 kills a week of the ONE best monster for each drop. tly_minesweep (floors 1 to
    /// 160, seven day counters, every monster on every floor killed through the game's own drop
    /// code, bare farmer) measured what clearing floors actually yields: 3.4 to 5.9 monsters a
    /// floor, so 240 to 410 kills a week spread over a band's whole roster. The common drops every
    /// monster gives (Slime, Bug Meat, Bat Wing, the essences) came out near the table; a drop that
    /// only one uncommon monster gives came out 3 to 25x under it. Jeff's rule: a single-monster
    /// drop is capped at TWICE the measured floor-clearing supply, rounded up, floor 2, so a player
    /// who does camp that monster gets credit without an ask nobody clearing floors can meet. Rows
    /// the sweep never saw at all (a monster deeper than Skull Cavern 40, or dangerous-mines only)
    /// are left to the generated table. Numbers: docs/superpowers/notes/minesweep-2026-09-16.md.
    /// Hand table; <see cref="MonsterDropsMeasured"/> is what the ask pass reads.</summary>
    public static readonly IReadOnlyDictionary<string, double> MonsterDropCaps = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)114"] = 2,    // Ancient Seed: Grubs, measured 0.8 a week
        ["(O)287"] = 20,   // Bomb: Lava Crabs, measured 10
        ["(O)881"] = 84,   // Bone Fragment: Skeletons, measured 42
        ["(O)286"] = 34,   // Cherry Bomb: Rock Crabs, measured 17
        ["(O)428"] = 20,   // Cloth: Mummies, measured 10
        ["(O)334"] = 8,    // Copper Bar: Metal Heads, measured 4
        ["(O)732"] = 9,    // Crab Cakes: Iridium Crabs, measured 4
        ["(O)717"] = 15,   // Crab: Lava Crabs, measured 7
        ["(O)414"] = 5,    // Crystal Fruit: Dust Spirits, measured 2
        ["(O)98"] = 4,     // Dwarf Scroll III: Frost Jellies, measured 2
        ["(O)86"] = 38,    // Earth Crystal: Duggies plus geodes, measured 19
        ["(O)156"] = 2,    // Ghostfish: Ghosts, measured 0.6
        ["(O)336"] = 3,    // Gold Bar: Squid Kids, measured 1.4
        ["(O)153"] = 24,   // Green Algae: Green Slimes, measured 12
        ["(O)335"] = 3,    // Iron Bar: Metal Heads, measured 1.4
        ["(O)288"] = 2,    // Mega Bomb: Squid Kids, measured 0.3
        ["(O)243"] = 4,    // Miner's Treat: Mummies, measured 2
        ["(O)338"] = 2,    // Refined Quartz: Ghosts, measured 1
        ["(O)273"] = 15,   // Rice Shoot: Grubs, measured 7.5
        ["(O)226"] = 6,    // Spicy Eel: Serpents, measured 3
        ["(O)814"] = 5,    // Squid Ink: Squid Kids, measured 2
        ["(O)203"] = 4,    // Strange Bun: Shadow Brutes and Shamans, measured 2
        ["(O)157"] = 22,   // White Algae: Sludges, measured 11
        ["(O)412"] = 25,   // Winter Root: Frost Jellies, measured 12
    };

    /// <summary>The generated <see cref="MonsterDrops"/> with <see cref="MonsterDropCaps"/> applied:
    /// the smaller of the two wherever a cap exists.</summary>
    public static readonly IReadOnlyDictionary<string, double> MonsterDropsMeasured = Capped(MonsterDrops, MonsterDropCaps);

    private static IReadOnlyDictionary<string, double> Capped(IReadOnlyDictionary<string, double> table, IReadOnlyDictionary<string, double> caps)
    {
        var result = new Dictionary<string, double>(StringComparer.Ordinal);
        foreach (KeyValuePair<string, double> row in table)
            result[row.Key] = caps.TryGetValue(row.Key, out double cap) ? Math.Min(row.Value, cap) : row.Value;
        return result;
    }

    /// <summary>Minerals (Data/Objects category -12), Jeff 2026-09-04: base 4; easier to hunt than a
    /// specific artifact. Gems stay single.</summary>
    public static readonly IReadOnlyDictionary<string, double> Minerals = new Dictionary<string, double>(StringComparer.Ordinal)
    {
        ["(O)541"] = 4,   // Aerinite
        ["(O)538"] = 4,   // Alamite
        ["(O)540"] = 4,   // Baryte
        ["(O)570"] = 4,   // Basalt
        ["(O)539"] = 4,   // Bixite
        ["(O)542"] = 4,   // Calcite
        ["(O)566"] = 4,   // Celestine
        ["(O)543"] = 4,   // Dolomite
        ["(O)544"] = 4,   // Esperite
        ["(O)577"] = 4,   // Fairy Stone
        ["(O)565"] = 4,   // Fire Opal
        ["(O)545"] = 4,   // Fluorapatite
        ["(O)546"] = 4,   // Geminite
        ["(O)561"] = 4,   // Ghost Crystal
        ["(O)569"] = 4,   // Granite
        ["(O)547"] = 4,   // Helvite
        ["(O)573"] = 4,   // Hematite
        ["(O)549"] = 4,   // Jagoite
        ["(O)548"] = 4,   // Jamborite
        ["(O)563"] = 4,   // Jasper
        ["(O)550"] = 4,   // Kyanite
        ["(O)554"] = 4,   // Lemon Stone
        ["(O)571"] = 4,   // Limestone
        ["(O)551"] = 4,   // Lunarite
        ["(O)552"] = 4,   // Malachite
        ["(O)567"] = 4,   // Marble
        ["(O)574"] = 4,   // Mudstone
        ["(O)555"] = 4,   // Nekoite
        ["(O)553"] = 4,   // Neptunite
        ["(O)575"] = 4,   // Obsidian
        ["(O)560"] = 4,   // Ocean Stone
        ["(O)564"] = 4,   // Opal
        ["(O)556"] = 4,   // Orpiment
        ["(O)557"] = 4,   // Petrified Slime
        ["(O)559"] = 4,   // Pyrite
        ["(O)568"] = 4,   // Sandstone
        ["(O)576"] = 4,   // Slate
        ["(O)572"] = 4,   // Soapstone
        ["(O)578"] = 4,   // Star Shards
        ["(O)558"] = 4,   // Thunder Egg
        ["(O)562"] = 4,   // Tigerseye
    };
}
