using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using StardewValley;
using TheLongestYear.Core;

namespace TheLongestYear.Debug
{
    /// <summary>Writes <c>item-effort-model.md</c>: every pool item by theme with its derived
    /// effort, tier (quartile within that theme's pool), source and basis, so Jeff reviews the
    /// numbers the rules produced rather than guesses (activity-themes spec, Phase 1).</summary>
    internal static class EffortDocWriter
    {
        public static string Render(
            ItemPools pools, IReadOnlyDictionary<string, RawObjectEntry> objects,
            ItemAvailabilityModel availability, string version)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# The Longest Year: item effort model");
            sb.AppendLine();
            sb.AppendLine($"Generated by `tly_dumpeffort` from live game data (mod version {version}).");
            sb.AppendLine();
            sb.AppendLine("Effort is on the scale the fish and metal rules already use (copper ore 1, iron 3, gold 5, iridium 7). "
                + "Tiers are quartiles of effort WITHIN each theme's pool, so Easy/Medium/Hard/Extreme are relative to what that theme can ask; "
                + "the weekly-goal sampler tiers the open lines on the live board the same way. "
                + "Source: derived = a rule read it from game data; price = no rule claimed the id, so the sale-price bucket stands; override = the curated effort override table.");
            sb.AppendLine();

            foreach (Theme theme in Enum.GetValues(typeof(Theme)))
            {
                IReadOnlyList<string> ids = ThemeEffortPools.IdsFor(theme, pools, objects);
                var rows = ids.Select(id => (Id: id, Availability: availability.For(id))).ToList();
                TierCutoffs cutoffs = EffortTiers.Cutoffs(rows.Select(r => r.Availability.Effort).ToList());
                sb.AppendLine($"## {theme} ({rows.Count} items; tier cutoffs easy <= {cutoffs.Easy}, medium <= {cutoffs.Medium}, hard <= {cutoffs.Hard})");
                sb.AppendLine();
                sb.AppendLine("| Item | Id | Effort | Tier | Source | Basis |");
                sb.AppendLine("|---|---|---|---|---|---|");
                foreach ((string id, ItemAvailability a) in rows.OrderBy(r => r.Availability.Effort).ThenBy(r => r.Id, StringComparer.Ordinal))
                    sb.AppendLine($"| {Name(id)} | {id} | {a.Effort} | {EffortTiers.Tier(a.Effort, cutoffs)} | {a.Source} | {a.Basis.Replace("|", "/")} |");
                sb.AppendLine();
            }
            return sb.ToString();
        }

        private static string Name(string id)
        {
            try { return ItemRegistry.GetDataOrErrorItem(id).DisplayName; }
            catch (Exception) { return id; }
        }
    }
}
