using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using StardewValley;
using TheLongestYear.Core;

namespace TheLongestYear.Debug
{
    /// <summary>Writes <c>item-effort-model.md</c>: every pool item by theme with its derived
    /// effort, tier (absolute effort band), source and basis, so Jeff reviews the numbers the
    /// rules produced rather than guesses (activity-themes spec, Phase 1).</summary>
    internal static class EffortDocWriter
    {
        public static string Render(
            ItemPools pools, IReadOnlyDictionary<string, RawObjectEntry> objects,
            ItemAvailabilityModel availability, string version)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# The Longest Year: item effort model");
            sb.AppendLine();
            sb.AppendLine($"Generated by `tly_dumpeffort` from live game data (mod version {version}).");
            sb.AppendLine();
            sb.AppendLine("Effort is on the scale the fish and metal rules already use (copper ore 1, iron 3, gold 5, iridium 7). "
                + $"Tiers are absolute bands on that scale (Easy 0-{EffortTiers.EasyMax}, Medium {EffortTiers.EasyMax + 1}-{EffortTiers.MediumMax}, Hard {EffortTiers.MediumMax + 1}-{EffortTiers.HardMax}, Extreme {EffortTiers.HardMax + 1}+), the same bands the weekly-goal sampler uses. "
                + "Source: derived = a rule read it from game data; price = no rule claimed the id, so the sale-price bucket stands; override = the curated effort override table.");
            sb.AppendLine();

            foreach (Theme theme in Enum.GetValues(typeof(Theme)))
            {
                IReadOnlyList<string> ids = ThemeEffortPools.IdsFor(theme, pools, objects);
                var rows = ids.Select(id => (Id: id, Availability: availability.For(id))).ToList();
                sb.AppendLine($"## {theme} ({rows.Count} items)");
                sb.AppendLine();
                sb.AppendLine("| Item | Id | Effort | Tier | Source | Basis |");
                sb.AppendLine("|---|---|---|---|---|---|");
                foreach ((string id, ItemAvailability a) in rows.OrderBy(r => r.Availability.Effort).ThenBy(r => r.Id, StringComparer.Ordinal))
                    sb.AppendLine($"| {Name(id)} | {id} | {a.Effort} | {EffortTiers.Tier(a.Effort)} | {a.Source} | {a.Basis.Replace("|", "/")} |");
                sb.AppendLine();
            }
            return sb.ToString();
        }

        private static string Name(string id)
        {
            try { return ItemRegistry.GetDataOrErrorItem(id).DisplayName; }
            catch (Exception) { return id; }
        }
    }
}
