using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using HarmonyLib;
using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewValley;
using StardewValley.Menus;
using StardewValley.Network;
using StardewValley.Quests;
using TheLongestYear.Core;
using TheLongestYear.Core.Availability;
using TheLongestYear.Donations;
using TheLongestYear.Integration;
using TheLongestYear.Loop;
using TheLongestYear.UI;

namespace TheLongestYear
{
    public sealed partial class ModEntry
    {
        private void CmdDumpBundles(string command, string[] args)
        {
            if (!Context.IsWorldReady)
            {
                this.Monitor.Log("Load a save first (the pools are derived from live game data).", LogLevel.Warn);
                return;
            }

            MetaState state = _meta.State;
            TheLongestYear.Core.DifficultyProfile difficulty = state.BoardDifficulty(_config);
            BundleGenerationTuning tuning = TheLongestYear.Core.DifficultyTuning.Scale(_config.PoolTuning, difficulty);
            var enginePoolReader = new TheLongestYear.Loop.GameDataPools(this.Monitor);
            ItemPools pools = enginePoolReader
                .Build(tuning, TheLongestYear.Core.YearTwoCrops.ExcludedFor(state.HasUpgrade, difficulty.Steps.ItemRarity),
                    TheLongestYear.Loop.BundleEngine.VanillaOnlyIdsFor(state.ModItemsOnBoard()));
            pools = TheLongestYear.Core.RarityBias.Apply(pools, difficulty.RarityBias, _config.RarityThresholds);

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# The Longest Year: engine bundle catalogue");
            sb.AppendLine();
            sb.AppendLine("Generated by `tly_dumpbundles` from live game data.");
            sb.AppendLine();
            sb.AppendLine("The engine picks ONE candidate per room position. For a bundle whose theme it recognises it discards the vanilla item list and re-rolls from a pool; otherwise it keeps vanilla's items exactly. Both kinds are listed here.");
            sb.AppendLine();

            AppendQuantityRules(sb, tuning, difficulty);
            AppendReachability(sb, enginePoolReader.LastReachability);
            AppendCandidates(sb, pools);
            AppendAuthored(sb);
            AppendPools(sb, pools);
            AppendThemePools(sb);

            string fileName = args.Length > 0 && !string.IsNullOrWhiteSpace(args[0])
                ? args[0] : "engine-bundle-catalogue.md";
            string path = System.IO.Path.Combine(this.Helper.DirectoryPath, fileName);
            System.IO.File.WriteAllText(path, sb.ToString());
            this.Monitor.Log($"tly_dumpbundles: wrote {path} ({sb.Length:N0} chars).", LogLevel.Info);
        }

        private void AppendQuantityRules(System.Text.StringBuilder sb, BundleGenerationTuning t, TheLongestYear.Core.DifficultyProfile d)
        {
            sb.AppendLine("## How quantities are decided");
            sb.AppendLine();
            sb.AppendLine("For a re-rolled slot the engine chooses the quantity itself, by pool:");
            sb.AppendLine();
            sb.AppendLine("| Pool | Quantity asked |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| Fish, forage, crops, crab pot, monster drops, station goods, animal products, geode minerals | basis x band: {d.AskBandLow:P0} to {d.AskBandHigh:P0} of a week's yield (fish: modelled best-day catches x7; forage: measured sweep mean; shop-seed crops and farmable Wild Seed crops: 99; crab pot: 10 pots; monsters: 60 kills a day; stations by unlock; minerals 4); gold keeps {AskBands.GoldFactor:P0}; legendaries 1 |");
            sb.AppendLine("| Books, artifacts, cooking, gems, anything else | 1 |");
            sb.AppendLine();
            sb.AppendLine($"Every quantity above except the banded fish and forage, and every quantity kept from vanilla, is then multiplied by the stack-size difficulty dial (currently **x{d.StackFactor}**, step {d.Steps.StackSize}), rounded away from zero, floored at 1 and **capped at 99**. Money bundles are never scaled.");
            sb.AppendLine();
            sb.AppendLine($"Quality: a re-rolled crop, forage or fish slot rolls {t.GoldQualityChance:P1} for gold then {t.SilverQualityChance:P1} for silver, and only ever on an item the game itself can star.");
            sb.AppendLine();
        }

        private void AppendReachability(System.Text.StringBuilder sb, SourceReachability reachability)
        {
            sb.AppendLine("## Items kept off the board");
            sb.AppendLine();
            if (reachability == null)
            {
                sb.AppendLine("Reachability was not available for this dump (the reads failed and the rule fails open, or it has not run on this reader). Nothing can be concluded about what is reachable this run; this is NOT the same as \"nothing was condemned\".");
                sb.AppendLine();
                return;
            }
            if (reachability.Reasons.Count == 0)
            {
                sb.AppendLine("Nothing. Every item in every pool has a route this run can reach.");
                sb.AppendLine();
                return;
            }
            sb.AppendLine($"{reachability.Reasons.Count} item(s) cannot be reached in a single loop:");
            sb.AppendLine();
            foreach (var reason in reachability.Reasons.OrderBy(r => r.Key, System.StringComparer.Ordinal))
                sb.AppendLine($"- **{reason.Key}**: {reason.Value}");
            sb.AppendLine();
        }

        private void AppendCandidates(System.Text.StringBuilder sb, ItemPools pools)
        {
            sb.AppendLine("## Bundles by room");
            sb.AppendLine();
            // The engine's FULL candidate set, authored bundles included. Reading the vanilla pool
            // alone understates every room: the mod's own bundles are widened into every position
            // of their room, which is exactly what gives several positions their alternates.
            TheLongestYear.Core.DifficultyProfile candidateDifficulty = _meta.State.BoardDifficulty(_config);
            var engine = new TheLongestYear.Loop.BundleEngine(
                this.Monitor, _config.PoolTuning, _config.EnableNonObjectDonations, _config.RarityThresholds,
                TheLongestYear.Core.YearTwoCrops.ExcludedFor(_meta.State.HasUpgrade, candidateDifficulty.Steps.ItemRarity),
                candidateDifficulty);
            engine.Availability = _availability;
            engine.AllowModItems = _meta.State.ModItemsOnBoard();
            int candidateSeed = BundleEngineSeed.For(
                unchecked((ulong)Game1.player.UniqueMultiplayerID), _meta.State.EffectiveBundleSeedLoop);
            var rooms = engine.BuildCandidatePools(pools, candidateSeed);

            foreach (var room in rooms.OrderBy(r => r.Key, System.StringComparer.Ordinal))
            {
                sb.AppendLine($"### {room.Key}");
                sb.AppendLine();
                for (int position = 0; position < room.Value.Count; position++)
                {
                    var candidates = room.Value[position];
                    if (candidates.Count == 0) continue;
                    // Vanilla folds every alternate BundleSets entry in as its own candidate, so the
                    // same bundle can appear several times at one position with an identical
                    // description. Collapse those: the reader wants the distinct possibilities.
                    var seen = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
                    var described = new System.Collections.Generic.List<string>();
                    bool passThrough = TheLongestYear.Loop.BundleEngine.IsPassThroughRoom(room.Key);
                    foreach (BundleSpec c in candidates)
                    {
                        DomainMatch match = PoolDomainClassifier.Classify(c, pools);
                        int shown = c.PickCount > 0 ? System.Math.Min(c.PickCount, c.Slots.Count) : c.Slots.Count;
                        string body;
                        if (passThrough)
                        {
                            // The Vault and the Abandoned Joja Mart never re-roll, whatever the
                            // classifier would say about their items in isolation.
                            body = $"  - Keeps vanilla's items: {DescribeSlots(c)}";
                        }
                        else if (match.Domain == PoolDomain.Recipe)
                        {
                            // "the Recipe pool" is not a pool anyone can look up: name the parts
                            // the bundle actually draws from (Jeff, 2026-08-29).
                            TheLongestYear.Core.PoolRecipe recipe = BundleSlotFiller.RecipeFor(c, pools, _availability);
                            body = recipe.IsVanillaOnly
                                ? $"  - Re-rolls from: {TheLongestYear.Core.BundlePoolRecipes.VanillaOnlyLabel} (no pool of its own): {DescribeSlots(c)}"
                                : $"  - Re-rolls from: {string.Join(", ", recipe.Parts.Select(p => p.Label))}."
                                    + " No item is asked for twice across the board; see the pool tables below.";
                        }
                        else if (match.Domain != PoolDomain.None)
                        {
                            string season = match.Season != null ? $", {match.Season} only (items specific to that season)" : "";
                            string rule = match.Domain == PoolDomain.Fish
                                ? (TheLongestYear.Core.FishBundleCandidates.IsNightFishingBundle(c)
                                    ? " Only fish that cannot be caught before 6pm, plus at most one Night Market fish."
                                    : TheLongestYear.Core.FishBundleCandidates.IsSpecialtyFishBundle(c)
                                        ? " Only hard-to-reach fish: legendaries, fish caught only in gated places (Secret Woods, desert, mines, Sewer, Night Market), or hard fish (difficulty 80+) that bite 8 hours a day or less, with at most one Night Market fish."
                                        : " Only fish from the water most of the bundle's vanilla fish share.")
                                    + " Never a jelly."
                                : " Any item in that pool can appear.";
                            body = $"  - Re-rolls from the **{match.Domain}** pool{season}.{rule} No item is asked for twice across the board; see the pool tables below.";
                        }
                        else
                        {
                            body = $"  - Keeps vanilla's items: {DescribeSlots(c)}";
                        }
                        string entry = $"- **{c.Name}** — shows {shown}, needs {c.NumberOfSlots}"
                            + System.Environment.NewLine + body;
                        if (seen.Add(entry))
                            described.Add(entry);
                    }

                    sb.AppendLine($"**Position {position}** — {described.Count} possible bundle(s):");
                    sb.AppendLine();
                    foreach (string entry in described)
                        sb.AppendLine(entry);
                    sb.AppendLine();
                }
            }
        }

        private static string DescribeSlots(BundleSpec spec)
            => string.Join(", ", spec.Slots.Select(s =>
            {
                if (s.ItemId == "-1") return $"{s.Stack}g";
                string q = s.Quality > 0 ? $" (quality {s.Quality})" : "";
                return $"{DisplayName(s.ItemId)} x{s.Stack}{q}";
            }));

        /// <summary>Activity-themes spec (2026-08-28): the simulated line counts that drove the
        /// merge from six narrow themes to three, and the effort override table (ships empty).</summary>
        private void AppendThemePools(System.Text.StringBuilder sb)
        {
            sb.AppendLine("## Theme pools");
            sb.AppendLine();
            sb.AppendLine("Spelunking, Artisan and Kitchen take goals by item kind from anywhere on the board. Open lines per board from the spec's 100,000-board simulation (uniform per slot, no repeats in a room):");
            sb.AppendLine();
            sb.AppendLine("| Domain | Lines per board (avg) | Boards with none |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Monster drops | 2.4 | 27% |");
            sb.AppendLine("| Artifacts | 3.4 | 23% |");
            sb.AppendLine("| Animal products | 3.5 | 5% |");
            sb.AppendLine("| Minerals + gems | 7.4 | (57% under 8) |");
            sb.AppendLine("| Cooked dishes | 7.4 | |");
            sb.AppendLine("| Artisan goods | 13.5 | |");
            sb.AppendLine("| Spelunking (minerals + gems + monster drops + artifacts) | 13.1 | 1.6% under 4 |");
            sb.AppendLine("| Kitchen (animal products + cooked dishes) | 24.5 | |");
            sb.AppendLine();
            sb.AppendLine("A Spring week asks for 4 goals, Winter for 7. A theme is only offered when it can ask for 2 or more this week (rule C); the per-item effort tiers that weight the draw are in `item-effort-model.md` (`tly_dumpeffort`).");
            sb.AppendLine();
            sb.AppendLine("### Effort overrides");
            sb.AppendLine();
            sb.AppendLine("None. The curated effort override table ships empty; a tier that looks wrong is fixed by fixing its derivation rule.");
            sb.AppendLine();
        }

        private void AppendPools(System.Text.StringBuilder sb, ItemPools pools)
        {
            sb.AppendLine("## The item pools");
            sb.AppendLine();
            sb.AppendLine("A bundle marked above as re-rolling can ask for any item in its pool, filtered by season where the bundle names one (and, for fish, by the habitat of the bundle it replaced).");
            sb.AppendLine();
            AppendPool(sb, "Seasonal Crops (also the Quality Crops pool, at gold)", pools.Crops);
            AppendPool(sb, "Seasonal Forage", pools.Forage);
            AppendPool(sb, "Fish", pools.Fish);
            AppendPool(sb, "Crab Pot", pools.CrabPot);
            AppendPool(sb, "Monster Drops", pools.MonsterDrops);
            AppendPool(sb, "Metals", pools.Metals);
            AppendPool(sb, "Artisan Goods", pools.ArtisanGoods);
            AppendPool(sb, "Artifacts (authored bundles)", pools.Artifacts);
            AppendPool(sb, "Books (authored bundles)", pools.Books);
            AppendPool(sb, "Saplings (authored bundles)", pools.Saplings);
            AppendPool(sb, "Geode Minerals (authored bundles)", pools.GeodeMinerals);
            AppendPool(sb, "Cooking (authored bundles)", pools.Cooking);
            AppendPool(sb, "Tapper Goods (authored bundles)", pools.TapperGoods);
        }

        private static void AppendPool(System.Text.StringBuilder sb, string title, System.Collections.Generic.IReadOnlyList<PoolItem> items)
        {
            sb.AppendLine($"### {title} — {items.Count} items");
            sb.AppendLine();
            if (items.Count == 0) { sb.AppendLine("_(empty)_"); sb.AppendLine(); return; }
            sb.AppendLine("| Item | Price | Seasons |");
            sb.AppendLine("|---|---|---|");
            foreach (PoolItem i in items.OrderBy(i => i.Price))
            {
                string seasons = i.Seasons.Count == 0 ? "any" : string.Join(" / ", i.Seasons);
                sb.AppendLine($"| {DisplayName(i.ItemId)} | {i.Price}g | {seasons} |");
            }
            sb.AppendLine();
        }

        private static void AppendAuthored(System.Text.StringBuilder sb)
        {
            sb.AppendLine("## Bundles authored by the mod");
            sb.AppendLine();
            sb.AppendLine("These are added as extra candidates to every position of their room, so any of them can displace a vanilla bundle. Their slots are composed once and are final: the engine never re-rolls them.");
            sb.AppendLine();
            sb.AppendLine("| Bundle | Room | Shows | Needs | Items drawn from | Quality |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var def in AuthoredBundleCatalog.All)
            {
                string source = def.Source == AuthoredSlotSource.FixedList
                    ? "fixed: " + string.Join(", ", def.FixedItemIds.Select(DisplayName))
                    : def.Source.ToString() + " pool";
                string quality = def.QualityAsk > 0 ? def.QualityAsk.ToString() : "any";
                sb.AppendLine($"| {def.Name} | {def.Room} | {def.SlotCount} | {def.NumberOfSlots} | {source} | {quality} |");
            }
            sb.AppendLine();
        }
    }
}
